/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DeRouteImport } from './routes/de'
import { Route as EnRouteImport } from './routes/en'
import { Route as EsRouteImport } from './routes/es'
import { Route as EsMxRouteImport } from './routes/es-mx'
import { Route as FrRouteImport } from './routes/fr'
import { Route as ItRouteImport } from './routes/it'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategoriaProdutoRouteImport } from './routes/$categoria.$produto'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogFeedDotxmlRouteImport } from './routes/blog.feed[.]xml'
import { Route as ComplianceAdsRouteImport } from './routes/compliance/ads'
import { Route as ComplianceCookiesRouteImport } from './routes/compliance/cookies'
import { Route as CompliancePrivacyRouteImport } from './routes/compliance/privacy'
import { Route as ComplianceReturnsRouteImport } from './routes/compliance/returns'
import { Route as ComplianceTermsRouteImport } from './routes/compliance/terms'
import { Route as DeSplatRouteImport } from './routes/de.$'
import { Route as EnSplatRouteImport } from './routes/en.$'
import { Route as EsMxSplatRouteImport } from './routes/es-mx.$'
import { Route as EsSplatRouteImport } from './routes/es.$'
import { Route as FrSplatRouteImport } from './routes/fr.$'
import { Route as ItSplatRouteImport } from './routes/it.$'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminAliexpressReviewsRouteImport } from './routes/_authenticated/admin.aliexpress-reviews'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated/admin.compliance'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminDiscoverRouteImport } from './routes/_authenticated/admin.discover'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as AuthenticatedAdminHomeRouteImport } from './routes/_authenticated/admin.home'
import { Route as AuthenticatedAdminHomeVisualRouteImport } from './routes/_authenticated/admin.home-visual'
import { Route as AuthenticatedAdminImportsRouteImport } from './routes/_authenticated/admin.imports'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminMapRouteImport } from './routes/_authenticated/admin.map'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin.marketing'
import { Route as AuthenticatedAdminOpportunitiesRouteImport } from './routes/_authenticated/admin.opportunities'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminPerformanceRouteImport } from './routes/_authenticated/admin.performance'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminRecoveryRouteImport } from './routes/_authenticated/admin.recovery'
import { Route as AuthenticatedAdminRyviuReviewsRouteImport } from './routes/_authenticated/admin.ryviu-reviews'
import { Route as AuthenticatedAdminSecureCredentialsRouteImport } from './routes/_authenticated/admin.secure-credentials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated/admin.whatsapp'
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated/checkout.index'
import { Route as AuthenticatedCheckoutOrderIdRouteImport } from './routes/_authenticated/checkout.$orderId'
import { Route as ApiPublicAbandonedCheckoutRouteImport } from './routes/api/public/abandoned-checkout'
import { Route as ApiPublicAliexpressReviewBrowserRouteImport } from './routes/api/public/aliexpress-review-browser'
import { Route as ApiPublicCommerceEventRouteImport } from './routes/api/public/commerce-event'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as AuthenticatedAdminCatalogIndexRouteImport } from './routes/_authenticated/admin.catalog.index'
import { Route as AuthenticatedAdminCatalogIdRouteImport } from './routes/_authenticated/admin.catalog.$id'
import { Route as AuthenticatedAdminImportsIdRouteImport } from './routes/_authenticated/admin.imports.$id'
import { Route as AuthenticatedAdminIntelligenceIndexRouteImport } from './routes/_authenticated/admin.intelligence.index'
import { Route as AuthenticatedAdminIntelligenceIdRouteImport } from './routes/_authenticated/admin.intelligence.$id'
import { Route as ApiPublicAliexpressStartRouteImport } from './routes/api/public/aliexpress.start'
import { Route as ApiPublicCronAliexpressStockRouteImport } from './routes/api/public/cron/aliexpress-stock'
import { Route as ApiPublicCronOrderEmailsRouteImport } from './routes/api/public/cron/order-emails'
import { Route as ApiPublicFeedsGoogleMerchantDotxmlRouteImport } from './routes/api/public/feeds/google-merchant[.]xml'
import { Route as ApiPublicFeedsMetaCatalogDotcsvRouteImport } from './routes/api/public/feeds/meta-catalog[.]csv'
import { Route as ApiPublicWebhooks17trackRouteImport } from './routes/api/public/webhooks/17track'
import { Route as ApiPublicWebhooksAliexpressRouteImport } from './routes/api/public/webhooks/aliexpress'
import { Route as ApiPublicWebhooksAmplopayRouteImport } from './routes/api/public/webhooks/amplopay'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'
import { Route as ApiPublicWebhooksEbanxRouteImport } from './routes/api/public/webhooks/ebanx'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksNupayRouteImport } from './routes/api/public/webhooks/nupay'
import { Route as ApiPublicWebhooksPagbankRouteImport } from './routes/api/public/webhooks/pagbank'
import { Route as ApiPublicWebhooksPaypalRouteImport } from './routes/api/public/webhooks/paypal'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EsMxRoute = EsMxRouteImport.update({
  id: '/es-mx',
  path: '/es-mx',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaProdutoRoute = CategoriaProdutoRouteImport.update({
  id: '/$categoria/$produto',
  path: '/$categoria/$produto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogFeedDotxmlRoute = BlogFeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => BlogRoute,
} as any)
const ComplianceAdsRoute = ComplianceAdsRouteImport.update({
  id: '/compliance/ads',
  path: '/compliance/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceCookiesRoute = ComplianceCookiesRouteImport.update({
  id: '/compliance/cookies',
  path: '/compliance/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CompliancePrivacyRoute = CompliancePrivacyRouteImport.update({
  id: '/compliance/privacy',
  path: '/compliance/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceReturnsRoute = ComplianceReturnsRouteImport.update({
  id: '/compliance/returns',
  path: '/compliance/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceTermsRoute = ComplianceTermsRouteImport.update({
  id: '/compliance/terms',
  path: '/compliance/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DeSplatRoute = DeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DeRoute,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EnRoute,
} as any)
const EsMxSplatRoute = EsMxSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EsMxRoute,
} as any)
const EsSplatRoute = EsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EsRoute,
} as any)
const FrSplatRoute = FrSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FrRoute,
} as any)
const ItSplatRoute = ItSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ItRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAliexpressReviewsRoute =
  AuthenticatedAdminAliexpressReviewsRouteImport.update({
    id: '/aliexpress-reviews',
    path: '/aliexpress-reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiscoverRoute =
  AuthenticatedAdminDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHomeRoute = AuthenticatedAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHomeVisualRoute =
  AuthenticatedAdminHomeVisualRouteImport.update({
    id: '/home-visual',
    path: '/home-visual',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportsRoute =
  AuthenticatedAdminImportsRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMapRoute = AuthenticatedAdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesRoute =
  AuthenticatedAdminOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerformanceRoute =
  AuthenticatedAdminPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecoveryRoute =
  AuthenticatedAdminRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRyviuReviewsRoute =
  AuthenticatedAdminRyviuReviewsRouteImport.update({
    id: '/ryviu-reviews',
    path: '/ryviu-reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSecureCredentialsRoute =
  AuthenticatedAdminSecureCredentialsRouteImport.update({
    id: '/secure-credentials',
    path: '/secure-credentials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCheckoutIndexRoute =
  AuthenticatedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutOrderIdRoute =
  AuthenticatedCheckoutOrderIdRouteImport.update({
    id: '/checkout/$orderId',
    path: '/checkout/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAbandonedCheckoutRoute =
  ApiPublicAbandonedCheckoutRouteImport.update({
    id: '/api/public/abandoned-checkout',
    path: '/api/public/abandoned-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAliexpressReviewBrowserRoute =
  ApiPublicAliexpressReviewBrowserRouteImport.update({
    id: '/api/public/aliexpress-review-browser',
    path: '/api/public/aliexpress-review-browser',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommerceEventRoute = ApiPublicCommerceEventRouteImport.update({
  id: '/api/public/commerce-event',
  path: '/api/public/commerce-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCatalogIndexRoute =
  AuthenticatedAdminCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogIdRoute =
  AuthenticatedAdminCatalogIdRouteImport.update({
    id: '/catalog/$id',
    path: '/catalog/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportsIdRoute =
  AuthenticatedAdminImportsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminImportsRoute,
  } as any)
const AuthenticatedAdminIntelligenceIndexRoute =
  AuthenticatedAdminIntelligenceIndexRouteImport.update({
    id: '/intelligence/',
    path: '/intelligence/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntelligenceIdRoute =
  AuthenticatedAdminIntelligenceIdRouteImport.update({
    id: '/intelligence/$id',
    path: '/intelligence/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicAliexpressStartRoute =
  ApiPublicAliexpressStartRouteImport.update({
    id: '/api/public/aliexpress/start',
    path: '/api/public/aliexpress/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAliexpressStockRoute =
  ApiPublicCronAliexpressStockRouteImport.update({
    id: '/api/public/cron/aliexpress-stock',
    path: '/api/public/cron/aliexpress-stock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronOrderEmailsRoute =
  ApiPublicCronOrderEmailsRouteImport.update({
    id: '/api/public/cron/order-emails',
    path: '/api/public/cron/order-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsGoogleMerchantDotxmlRoute =
  ApiPublicFeedsGoogleMerchantDotxmlRouteImport.update({
    id: '/api/public/feeds/google-merchant.xml',
    path: '/api/public/feeds/google-merchant.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsMetaCatalogDotcsvRoute =
  ApiPublicFeedsMetaCatalogDotcsvRouteImport.update({
    id: '/api/public/feeds/meta-catalog.csv',
    path: '/api/public/feeds/meta-catalog.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooks17trackRoute =
  ApiPublicWebhooks17trackRouteImport.update({
    id: '/api/public/webhooks/17track',
    path: '/api/public/webhooks/17track',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAliexpressRoute =
  ApiPublicWebhooksAliexpressRouteImport.update({
    id: '/api/public/webhooks/aliexpress',
    path: '/api/public/webhooks/aliexpress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAmplopayRoute =
  ApiPublicWebhooksAmplopayRouteImport.update({
    id: '/api/public/webhooks/amplopay',
    path: '/api/public/webhooks/amplopay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksEbanxRoute = ApiPublicWebhooksEbanxRouteImport.update({
  id: '/api/public/webhooks/ebanx',
  path: '/api/public/webhooks/ebanx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNupayRoute = ApiPublicWebhooksNupayRouteImport.update({
  id: '/api/public/webhooks/nupay',
  path: '/api/public/webhooks/nupay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPagbankRoute =
  ApiPublicWebhooksPagbankRouteImport.update({
    id: '/api/public/webhooks/pagbank',
    path: '/api/public/webhooks/pagbank',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaypalRoute = ApiPublicWebhooksPaypalRouteImport.update({
  id: '/api/public/webhooks/paypal',
  path: '/api/public/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/es-mx': typeof EsMxRouteWithChildren
  '/fr': typeof FrRouteWithChildren
  '/it': typeof ItRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$categoria/$produto': typeof CategoriaProdutoRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/compliance/ads': typeof ComplianceAdsRoute
  '/compliance/cookies': typeof ComplianceCookiesRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/returns': typeof ComplianceReturnsRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/de/$': typeof DeSplatRoute
  '/en/$': typeof EnSplatRoute
  '/es-mx/$': typeof EsMxSplatRoute
  '/es/$': typeof EsSplatRoute
  '/fr/$': typeof FrSplatRoute
  '/it/$': typeof ItSplatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/aliexpress-reviews': typeof AuthenticatedAdminAliexpressReviewsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/discover': typeof AuthenticatedAdminDiscoverRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/home-visual': typeof AuthenticatedAdminHomeVisualRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRouteWithChildren
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/map': typeof AuthenticatedAdminMapRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/admin/ryviu-reviews': typeof AuthenticatedAdminRyviuReviewsRoute
  '/admin/secure-credentials': typeof AuthenticatedAdminSecureCredentialsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/api/public/abandoned-checkout': typeof ApiPublicAbandonedCheckoutRoute
  '/api/public/aliexpress-review-browser': typeof ApiPublicAliexpressReviewBrowserRoute
  '/api/public/commerce-event': typeof ApiPublicCommerceEventRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/admin/catalog/$id': typeof AuthenticatedAdminCatalogIdRoute
  '/admin/imports/$id': typeof AuthenticatedAdminImportsIdRoute
  '/admin/intelligence/$id': typeof AuthenticatedAdminIntelligenceIdRoute
  '/api/public/aliexpress/start': typeof ApiPublicAliexpressStartRoute
  '/api/public/cron/aliexpress-stock': typeof ApiPublicCronAliexpressStockRoute
  '/api/public/cron/order-emails': typeof ApiPublicCronOrderEmailsRoute
  '/api/public/feeds/google-merchant.xml': typeof ApiPublicFeedsGoogleMerchantDotxmlRoute
  '/api/public/feeds/meta-catalog.csv': typeof ApiPublicFeedsMetaCatalogDotcsvRoute
  '/api/public/webhooks/17track': typeof ApiPublicWebhooks17trackRoute
  '/api/public/webhooks/aliexpress': typeof ApiPublicWebhooksAliexpressRoute
  '/api/public/webhooks/amplopay': typeof ApiPublicWebhooksAmplopayRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/api/public/webhooks/ebanx': typeof ApiPublicWebhooksEbanxRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/nupay': typeof ApiPublicWebhooksNupayRoute
  '/api/public/webhooks/pagbank': typeof ApiPublicWebhooksPagbankRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/admin/catalog/': typeof AuthenticatedAdminCatalogIndexRoute
  '/admin/intelligence/': typeof AuthenticatedAdminIntelligenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/es-mx': typeof EsMxRouteWithChildren
  '/fr': typeof FrRouteWithChildren
  '/it': typeof ItRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$categoria/$produto': typeof CategoriaProdutoRoute
  '/account': typeof AuthenticatedAccountRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/compliance/ads': typeof ComplianceAdsRoute
  '/compliance/cookies': typeof ComplianceCookiesRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/returns': typeof ComplianceReturnsRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/de/$': typeof DeSplatRoute
  '/en/$': typeof EnSplatRoute
  '/es-mx/$': typeof EsMxSplatRoute
  '/es/$': typeof EsSplatRoute
  '/fr/$': typeof FrSplatRoute
  '/it/$': typeof ItSplatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/aliexpress-reviews': typeof AuthenticatedAdminAliexpressReviewsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/discover': typeof AuthenticatedAdminDiscoverRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/home-visual': typeof AuthenticatedAdminHomeVisualRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRouteWithChildren
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/map': typeof AuthenticatedAdminMapRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/admin/ryviu-reviews': typeof AuthenticatedAdminRyviuReviewsRoute
  '/admin/secure-credentials': typeof AuthenticatedAdminSecureCredentialsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/api/public/abandoned-checkout': typeof ApiPublicAbandonedCheckoutRoute
  '/api/public/aliexpress-review-browser': typeof ApiPublicAliexpressReviewBrowserRoute
  '/api/public/commerce-event': typeof ApiPublicCommerceEventRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/checkout': typeof AuthenticatedCheckoutIndexRoute
  '/admin/catalog/$id': typeof AuthenticatedAdminCatalogIdRoute
  '/admin/imports/$id': typeof AuthenticatedAdminImportsIdRoute
  '/admin/intelligence/$id': typeof AuthenticatedAdminIntelligenceIdRoute
  '/api/public/aliexpress/start': typeof ApiPublicAliexpressStartRoute
  '/api/public/cron/aliexpress-stock': typeof ApiPublicCronAliexpressStockRoute
  '/api/public/cron/order-emails': typeof ApiPublicCronOrderEmailsRoute
  '/api/public/feeds/google-merchant.xml': typeof ApiPublicFeedsGoogleMerchantDotxmlRoute
  '/api/public/feeds/meta-catalog.csv': typeof ApiPublicFeedsMetaCatalogDotcsvRoute
  '/api/public/webhooks/17track': typeof ApiPublicWebhooks17trackRoute
  '/api/public/webhooks/aliexpress': typeof ApiPublicWebhooksAliexpressRoute
  '/api/public/webhooks/amplopay': typeof ApiPublicWebhooksAmplopayRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/api/public/webhooks/ebanx': typeof ApiPublicWebhooksEbanxRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/nupay': typeof ApiPublicWebhooksNupayRoute
  '/api/public/webhooks/pagbank': typeof ApiPublicWebhooksPagbankRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogIndexRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/es-mx': typeof EsMxRouteWithChildren
  '/fr': typeof FrRouteWithChildren
  '/it': typeof ItRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$categoria/$produto': typeof CategoriaProdutoRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/compliance/ads': typeof ComplianceAdsRoute
  '/compliance/cookies': typeof ComplianceCookiesRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/returns': typeof ComplianceReturnsRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/de/$': typeof DeSplatRoute
  '/en/$': typeof EnSplatRoute
  '/es-mx/$': typeof EsMxSplatRoute
  '/es/$': typeof EsSplatRoute
  '/fr/$': typeof FrSplatRoute
  '/it/$': typeof ItSplatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/aliexpress-reviews': typeof AuthenticatedAdminAliexpressReviewsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/discover': typeof AuthenticatedAdminDiscoverRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/home': typeof AuthenticatedAdminHomeRoute
  '/_authenticated/admin/home-visual': typeof AuthenticatedAdminHomeVisualRoute
  '/_authenticated/admin/imports': typeof AuthenticatedAdminImportsRouteWithChildren
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/map': typeof AuthenticatedAdminMapRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/_authenticated/admin/ryviu-reviews': typeof AuthenticatedAdminRyviuReviewsRoute
  '/_authenticated/admin/secure-credentials': typeof AuthenticatedAdminSecureCredentialsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/api/public/abandoned-checkout': typeof ApiPublicAbandonedCheckoutRoute
  '/api/public/aliexpress-review-browser': typeof ApiPublicAliexpressReviewBrowserRoute
  '/api/public/commerce-event': typeof ApiPublicCommerceEventRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/_authenticated/admin/catalog/$id': typeof AuthenticatedAdminCatalogIdRoute
  '/_authenticated/admin/imports/$id': typeof AuthenticatedAdminImportsIdRoute
  '/_authenticated/admin/intelligence/$id': typeof AuthenticatedAdminIntelligenceIdRoute
  '/api/public/aliexpress/start': typeof ApiPublicAliexpressStartRoute
  '/api/public/cron/aliexpress-stock': typeof ApiPublicCronAliexpressStockRoute
  '/api/public/cron/order-emails': typeof ApiPublicCronOrderEmailsRoute
  '/api/public/feeds/google-merchant.xml': typeof ApiPublicFeedsGoogleMerchantDotxmlRoute
  '/api/public/feeds/meta-catalog.csv': typeof ApiPublicFeedsMetaCatalogDotcsvRoute
  '/api/public/webhooks/17track': typeof ApiPublicWebhooks17trackRoute
  '/api/public/webhooks/aliexpress': typeof ApiPublicWebhooksAliexpressRoute
  '/api/public/webhooks/amplopay': typeof ApiPublicWebhooksAmplopayRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/api/public/webhooks/ebanx': typeof ApiPublicWebhooksEbanxRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/nupay': typeof ApiPublicWebhooksNupayRoute
  '/api/public/webhooks/pagbank': typeof ApiPublicWebhooksPagbankRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/_authenticated/admin/catalog/': typeof AuthenticatedAdminCatalogIndexRoute
  '/_authenticated/admin/intelligence/': typeof AuthenticatedAdminIntelligenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/de'
    | '/en'
    | '/es'
    | '/es-mx'
    | '/fr'
    | '/it'
    | '/products'
    | '/sitemap.xml'
    | '/$categoria/$produto'
    | '/account'
    | '/admin'
    | '/favorites'
    | '/orders'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/compliance/ads'
    | '/compliance/cookies'
    | '/compliance/privacy'
    | '/compliance/returns'
    | '/compliance/terms'
    | '/de/$'
    | '/en/$'
    | '/es-mx/$'
    | '/es/$'
    | '/fr/$'
    | '/it/$'
    | '/products/$slug'
    | '/admin/ai'
    | '/admin/aliexpress-reviews'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/compliance'
    | '/admin/dashboard'
    | '/admin/discover'
    | '/admin/email'
    | '/admin/home'
    | '/admin/home-visual'
    | '/admin/imports'
    | '/admin/integrations'
    | '/admin/map'
    | '/admin/marketing'
    | '/admin/opportunities'
    | '/admin/orders'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/recovery'
    | '/admin/ryviu-reviews'
    | '/admin/secure-credentials'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/checkout/$orderId'
    | '/api/public/abandoned-checkout'
    | '/api/public/aliexpress-review-browser'
    | '/api/public/commerce-event'
    | '/api/public/geo'
    | '/admin/'
    | '/checkout/'
    | '/admin/catalog/$id'
    | '/admin/imports/$id'
    | '/admin/intelligence/$id'
    | '/api/public/aliexpress/start'
    | '/api/public/cron/aliexpress-stock'
    | '/api/public/cron/order-emails'
    | '/api/public/feeds/google-merchant.xml'
    | '/api/public/feeds/meta-catalog.csv'
    | '/api/public/webhooks/17track'
    | '/api/public/webhooks/aliexpress'
    | '/api/public/webhooks/amplopay'
    | '/api/public/webhooks/asaas'
    | '/api/public/webhooks/ebanx'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/nupay'
    | '/api/public/webhooks/pagbank'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/whatsapp'
    | '/admin/catalog/'
    | '/admin/intelligence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/de'
    | '/en'
    | '/es'
    | '/es-mx'
    | '/fr'
    | '/it'
    | '/products'
    | '/sitemap.xml'
    | '/$categoria/$produto'
    | '/account'
    | '/favorites'
    | '/orders'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/compliance/ads'
    | '/compliance/cookies'
    | '/compliance/privacy'
    | '/compliance/returns'
    | '/compliance/terms'
    | '/de/$'
    | '/en/$'
    | '/es-mx/$'
    | '/es/$'
    | '/fr/$'
    | '/it/$'
    | '/products/$slug'
    | '/admin/ai'
    | '/admin/aliexpress-reviews'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/compliance'
    | '/admin/dashboard'
    | '/admin/discover'
    | '/admin/email'
    | '/admin/home'
    | '/admin/home-visual'
    | '/admin/imports'
    | '/admin/integrations'
    | '/admin/map'
    | '/admin/marketing'
    | '/admin/opportunities'
    | '/admin/orders'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/recovery'
    | '/admin/ryviu-reviews'
    | '/admin/secure-credentials'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/checkout/$orderId'
    | '/api/public/abandoned-checkout'
    | '/api/public/aliexpress-review-browser'
    | '/api/public/commerce-event'
    | '/api/public/geo'
    | '/admin'
    | '/checkout'
    | '/admin/catalog/$id'
    | '/admin/imports/$id'
    | '/admin/intelligence/$id'
    | '/api/public/aliexpress/start'
    | '/api/public/cron/aliexpress-stock'
    | '/api/public/cron/order-emails'
    | '/api/public/feeds/google-merchant.xml'
    | '/api/public/feeds/meta-catalog.csv'
    | '/api/public/webhooks/17track'
    | '/api/public/webhooks/aliexpress'
    | '/api/public/webhooks/amplopay'
    | '/api/public/webhooks/asaas'
    | '/api/public/webhooks/ebanx'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/nupay'
    | '/api/public/webhooks/pagbank'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/whatsapp'
    | '/admin/catalog'
    | '/admin/intelligence'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/de'
    | '/en'
    | '/es'
    | '/es-mx'
    | '/fr'
    | '/it'
    | '/products'
    | '/sitemap.xml'
    | '/$categoria/$produto'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/orders'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/compliance/ads'
    | '/compliance/cookies'
    | '/compliance/privacy'
    | '/compliance/returns'
    | '/compliance/terms'
    | '/de/$'
    | '/en/$'
    | '/es-mx/$'
    | '/es/$'
    | '/fr/$'
    | '/it/$'
    | '/products/$slug'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/aliexpress-reviews'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/discover'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/home'
    | '/_authenticated/admin/home-visual'
    | '/_authenticated/admin/imports'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/map'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/opportunities'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/performance'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/recovery'
    | '/_authenticated/admin/ryviu-reviews'
    | '/_authenticated/admin/secure-credentials'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/checkout/$orderId'
    | '/api/public/abandoned-checkout'
    | '/api/public/aliexpress-review-browser'
    | '/api/public/commerce-event'
    | '/api/public/geo'
    | '/_authenticated/admin/'
    | '/_authenticated/checkout/'
    | '/_authenticated/admin/catalog/$id'
    | '/_authenticated/admin/imports/$id'
    | '/_authenticated/admin/intelligence/$id'
    | '/api/public/aliexpress/start'
    | '/api/public/cron/aliexpress-stock'
    | '/api/public/cron/order-emails'
    | '/api/public/feeds/google-merchant.xml'
    | '/api/public/feeds/meta-catalog.csv'
    | '/api/public/webhooks/17track'
    | '/api/public/webhooks/aliexpress'
    | '/api/public/webhooks/amplopay'
    | '/api/public/webhooks/asaas'
    | '/api/public/webhooks/ebanx'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/nupay'
    | '/api/public/webhooks/pagbank'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/whatsapp'
    | '/_authenticated/admin/catalog/'
    | '/_authenticated/admin/intelligence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  DeRoute: typeof DeRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  EsRoute: typeof EsRouteWithChildren
  EsMxRoute: typeof EsMxRouteWithChildren
  FrRoute: typeof FrRouteWithChildren
  ItRoute: typeof ItRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoriaProdutoRoute: typeof CategoriaProdutoRoute
  ComplianceAdsRoute: typeof ComplianceAdsRoute
  ComplianceCookiesRoute: typeof ComplianceCookiesRoute
  CompliancePrivacyRoute: typeof CompliancePrivacyRoute
  ComplianceReturnsRoute: typeof ComplianceReturnsRoute
  ComplianceTermsRoute: typeof ComplianceTermsRoute
  ApiPublicAbandonedCheckoutRoute: typeof ApiPublicAbandonedCheckoutRoute
  ApiPublicAliexpressReviewBrowserRoute: typeof ApiPublicAliexpressReviewBrowserRoute
  ApiPublicCommerceEventRoute: typeof ApiPublicCommerceEventRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiPublicAliexpressStartRoute: typeof ApiPublicAliexpressStartRoute
  ApiPublicCronAliexpressStockRoute: typeof ApiPublicCronAliexpressStockRoute
  ApiPublicCronOrderEmailsRoute: typeof ApiPublicCronOrderEmailsRoute
  ApiPublicFeedsGoogleMerchantDotxmlRoute: typeof ApiPublicFeedsGoogleMerchantDotxmlRoute
  ApiPublicFeedsMetaCatalogDotcsvRoute: typeof ApiPublicFeedsMetaCatalogDotcsvRoute
  ApiPublicWebhooks17trackRoute: typeof ApiPublicWebhooks17trackRoute
  ApiPublicWebhooksAliexpressRoute: typeof ApiPublicWebhooksAliexpressRoute
  ApiPublicWebhooksAmplopayRoute: typeof ApiPublicWebhooksAmplopayRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
  ApiPublicWebhooksEbanxRoute: typeof ApiPublicWebhooksEbanxRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksNupayRoute: typeof ApiPublicWebhooksNupayRoute
  ApiPublicWebhooksPagbankRoute: typeof ApiPublicWebhooksPagbankRoute
  ApiPublicWebhooksPaypalRoute: typeof ApiPublicWebhooksPaypalRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es-mx': {
      id: '/es-mx'
      path: '/es-mx'
      fullPath: '/es-mx'
      preLoaderRoute: typeof EsMxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoria/$produto': {
      id: '/$categoria/$produto'
      path: '/$categoria/$produto'
      fullPath: '/$categoria/$produto'
      preLoaderRoute: typeof CategoriaProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/feed.xml': {
      id: '/blog/feed.xml'
      path: '/feed.xml'
      fullPath: '/blog/feed.xml'
      preLoaderRoute: typeof BlogFeedDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/compliance/ads': {
      id: '/compliance/ads'
      path: '/compliance/ads'
      fullPath: '/compliance/ads'
      preLoaderRoute: typeof ComplianceAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/cookies': {
      id: '/compliance/cookies'
      path: '/compliance/cookies'
      fullPath: '/compliance/cookies'
      preLoaderRoute: typeof ComplianceCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/privacy': {
      id: '/compliance/privacy'
      path: '/compliance/privacy'
      fullPath: '/compliance/privacy'
      preLoaderRoute: typeof CompliancePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/returns': {
      id: '/compliance/returns'
      path: '/compliance/returns'
      fullPath: '/compliance/returns'
      preLoaderRoute: typeof ComplianceReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/terms': {
      id: '/compliance/terms'
      path: '/compliance/terms'
      fullPath: '/compliance/terms'
      preLoaderRoute: typeof ComplianceTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/$': {
      id: '/de/$'
      path: '/$'
      fullPath: '/de/$'
      preLoaderRoute: typeof DeSplatRouteImport
      parentRoute: typeof DeRoute
    }
    '/en/$': {
      id: '/en/$'
      path: '/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof EnRoute
    }
    '/es-mx/$': {
      id: '/es-mx/$'
      path: '/$'
      fullPath: '/es-mx/$'
      preLoaderRoute: typeof EsMxSplatRouteImport
      parentRoute: typeof EsMxRoute
    }
    '/es/$': {
      id: '/es/$'
      path: '/$'
      fullPath: '/es/$'
      preLoaderRoute: typeof EsSplatRouteImport
      parentRoute: typeof EsRoute
    }
    '/fr/$': {
      id: '/fr/$'
      path: '/$'
      fullPath: '/fr/$'
      preLoaderRoute: typeof FrSplatRouteImport
      parentRoute: typeof FrRoute
    }
    '/it/$': {
      id: '/it/$'
      path: '/$'
      fullPath: '/it/$'
      preLoaderRoute: typeof ItSplatRouteImport
      parentRoute: typeof ItRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aliexpress-reviews': {
      id: '/_authenticated/admin/aliexpress-reviews'
      path: '/aliexpress-reviews'
      fullPath: '/admin/aliexpress-reviews'
      preLoaderRoute: typeof AuthenticatedAdminAliexpressReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/discover': {
      id: '/_authenticated/admin/discover'
      path: '/discover'
      fullPath: '/admin/discover'
      preLoaderRoute: typeof AuthenticatedAdminDiscoverRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/home': {
      id: '/_authenticated/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AuthenticatedAdminHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/home-visual': {
      id: '/_authenticated/admin/home-visual'
      path: '/home-visual'
      fullPath: '/admin/home-visual'
      preLoaderRoute: typeof AuthenticatedAdminHomeVisualRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imports': {
      id: '/_authenticated/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthenticatedAdminImportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/map': {
      id: '/_authenticated/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AuthenticatedAdminMapRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/opportunities': {
      id: '/_authenticated/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/performance': {
      id: '/_authenticated/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recovery': {
      id: '/_authenticated/admin/recovery'
      path: '/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AuthenticatedAdminRecoveryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ryviu-reviews': {
      id: '/_authenticated/admin/ryviu-reviews'
      path: '/ryviu-reviews'
      fullPath: '/admin/ryviu-reviews'
      preLoaderRoute: typeof AuthenticatedAdminRyviuReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/secure-credentials': {
      id: '/_authenticated/admin/secure-credentials'
      path: '/secure-credentials'
      fullPath: '/admin/secure-credentials'
      preLoaderRoute: typeof AuthenticatedAdminSecureCredentialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/checkout/': {
      id: '/_authenticated/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$orderId': {
      id: '/_authenticated/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof AuthenticatedCheckoutOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/abandoned-checkout': {
      id: '/api/public/abandoned-checkout'
      path: '/api/public/abandoned-checkout'
      fullPath: '/api/public/abandoned-checkout'
      preLoaderRoute: typeof ApiPublicAbandonedCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aliexpress-review-browser': {
      id: '/api/public/aliexpress-review-browser'
      path: '/api/public/aliexpress-review-browser'
      fullPath: '/api/public/aliexpress-review-browser'
      preLoaderRoute: typeof ApiPublicAliexpressReviewBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commerce-event': {
      id: '/api/public/commerce-event'
      path: '/api/public/commerce-event'
      fullPath: '/api/public/commerce-event'
      preLoaderRoute: typeof ApiPublicCommerceEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/catalog/': {
      id: '/_authenticated/admin/catalog/'
      path: '/catalog'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog/$id': {
      id: '/_authenticated/admin/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/admin/catalog/$id'
      preLoaderRoute: typeof AuthenticatedAdminCatalogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imports/$id': {
      id: '/_authenticated/admin/imports/$id'
      path: '/$id'
      fullPath: '/admin/imports/$id'
      preLoaderRoute: typeof AuthenticatedAdminImportsIdRouteImport
      parentRoute: typeof AuthenticatedAdminImportsRoute
    }
    '/_authenticated/admin/intelligence/': {
      id: '/_authenticated/admin/intelligence/'
      path: '/intelligence'
      fullPath: '/admin/intelligence/'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intelligence/$id': {
      id: '/_authenticated/admin/intelligence/$id'
      path: '/intelligence/$id'
      fullPath: '/admin/intelligence/$id'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/aliexpress/start': {
      id: '/api/public/aliexpress/start'
      path: '/api/public/aliexpress/start'
      fullPath: '/api/public/aliexpress/start'
      preLoaderRoute: typeof ApiPublicAliexpressStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/aliexpress-stock': {
      id: '/api/public/cron/aliexpress-stock'
      path: '/api/public/cron/aliexpress-stock'
      fullPath: '/api/public/cron/aliexpress-stock'
      preLoaderRoute: typeof ApiPublicCronAliexpressStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/order-emails': {
      id: '/api/public/cron/order-emails'
      path: '/api/public/cron/order-emails'
      fullPath: '/api/public/cron/order-emails'
      preLoaderRoute: typeof ApiPublicCronOrderEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/google-merchant.xml': {
      id: '/api/public/feeds/google-merchant.xml'
      path: '/api/public/feeds/google-merchant.xml'
      fullPath: '/api/public/feeds/google-merchant.xml'
      preLoaderRoute: typeof ApiPublicFeedsGoogleMerchantDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/meta-catalog.csv': {
      id: '/api/public/feeds/meta-catalog.csv'
      path: '/api/public/feeds/meta-catalog.csv'
      fullPath: '/api/public/feeds/meta-catalog.csv'
      preLoaderRoute: typeof ApiPublicFeedsMetaCatalogDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/17track': {
      id: '/api/public/webhooks/17track'
      path: '/api/public/webhooks/17track'
      fullPath: '/api/public/webhooks/17track'
      preLoaderRoute: typeof ApiPublicWebhooks17trackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/aliexpress': {
      id: '/api/public/webhooks/aliexpress'
      path: '/api/public/webhooks/aliexpress'
      fullPath: '/api/public/webhooks/aliexpress'
      preLoaderRoute: typeof ApiPublicWebhooksAliexpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/amplopay': {
      id: '/api/public/webhooks/amplopay'
      path: '/api/public/webhooks/amplopay'
      fullPath: '/api/public/webhooks/amplopay'
      preLoaderRoute: typeof ApiPublicWebhooksAmplopayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ebanx': {
      id: '/api/public/webhooks/ebanx'
      path: '/api/public/webhooks/ebanx'
      fullPath: '/api/public/webhooks/ebanx'
      preLoaderRoute: typeof ApiPublicWebhooksEbanxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nupay': {
      id: '/api/public/webhooks/nupay'
      path: '/api/public/webhooks/nupay'
      fullPath: '/api/public/webhooks/nupay'
      preLoaderRoute: typeof ApiPublicWebhooksNupayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pagbank': {
      id: '/api/public/webhooks/pagbank'
      path: '/api/public/webhooks/pagbank'
      fullPath: '/api/public/webhooks/pagbank'
      preLoaderRoute: typeof ApiPublicWebhooksPagbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paypal': {
      id: '/api/public/webhooks/paypal'
      path: '/api/public/webhooks/paypal'
      fullPath: '/api/public/webhooks/paypal'
      preLoaderRoute: typeof ApiPublicWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminImportsRouteChildren {
  AuthenticatedAdminImportsIdRoute: typeof AuthenticatedAdminImportsIdRoute
}

const AuthenticatedAdminImportsRouteChildren: AuthenticatedAdminImportsRouteChildren =
  {
    AuthenticatedAdminImportsIdRoute: AuthenticatedAdminImportsIdRoute,
  }

const AuthenticatedAdminImportsRouteWithChildren =
  AuthenticatedAdminImportsRoute._addFileChildren(
    AuthenticatedAdminImportsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAliexpressReviewsRoute: typeof AuthenticatedAdminAliexpressReviewsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDiscoverRoute: typeof AuthenticatedAdminDiscoverRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminHomeRoute: typeof AuthenticatedAdminHomeRoute
  AuthenticatedAdminHomeVisualRoute: typeof AuthenticatedAdminHomeVisualRoute
  AuthenticatedAdminImportsRoute: typeof AuthenticatedAdminImportsRouteWithChildren
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminMapRoute: typeof AuthenticatedAdminMapRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminOpportunitiesRoute: typeof AuthenticatedAdminOpportunitiesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPerformanceRoute: typeof AuthenticatedAdminPerformanceRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminRecoveryRoute: typeof AuthenticatedAdminRecoveryRoute
  AuthenticatedAdminRyviuReviewsRoute: typeof AuthenticatedAdminRyviuReviewsRoute
  AuthenticatedAdminSecureCredentialsRoute: typeof AuthenticatedAdminSecureCredentialsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCatalogIdRoute: typeof AuthenticatedAdminCatalogIdRoute
  AuthenticatedAdminIntelligenceIdRoute: typeof AuthenticatedAdminIntelligenceIdRoute
  AuthenticatedAdminCatalogIndexRoute: typeof AuthenticatedAdminCatalogIndexRoute
  AuthenticatedAdminIntelligenceIndexRoute: typeof AuthenticatedAdminIntelligenceIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAliexpressReviewsRoute:
    AuthenticatedAdminAliexpressReviewsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDiscoverRoute: AuthenticatedAdminDiscoverRoute,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminHomeRoute: AuthenticatedAdminHomeRoute,
  AuthenticatedAdminHomeVisualRoute: AuthenticatedAdminHomeVisualRoute,
  AuthenticatedAdminImportsRoute: AuthenticatedAdminImportsRouteWithChildren,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminMapRoute: AuthenticatedAdminMapRoute,
  AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
  AuthenticatedAdminOpportunitiesRoute: AuthenticatedAdminOpportunitiesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPerformanceRoute: AuthenticatedAdminPerformanceRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminRecoveryRoute: AuthenticatedAdminRecoveryRoute,
  AuthenticatedAdminRyviuReviewsRoute: AuthenticatedAdminRyviuReviewsRoute,
  AuthenticatedAdminSecureCredentialsRoute:
    AuthenticatedAdminSecureCredentialsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCatalogIdRoute: AuthenticatedAdminCatalogIdRoute,
  AuthenticatedAdminIntelligenceIdRoute: AuthenticatedAdminIntelligenceIdRoute,
  AuthenticatedAdminCatalogIndexRoute: AuthenticatedAdminCatalogIndexRoute,
  AuthenticatedAdminIntelligenceIndexRoute:
    AuthenticatedAdminIntelligenceIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedCheckoutOrderIdRoute: typeof AuthenticatedCheckoutOrderIdRoute
  AuthenticatedCheckoutIndexRoute: typeof AuthenticatedCheckoutIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedCheckoutOrderIdRoute: AuthenticatedCheckoutOrderIdRoute,
  AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogFeedDotxmlRoute: typeof BlogFeedDotxmlRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogFeedDotxmlRoute: BlogFeedDotxmlRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DeRouteChildren {
  DeSplatRoute: typeof DeSplatRoute
}

const DeRouteChildren: DeRouteChildren = {
  DeSplatRoute: DeSplatRoute,
}

const DeRouteWithChildren = DeRoute._addFileChildren(DeRouteChildren)

interface EnRouteChildren {
  EnSplatRoute: typeof EnSplatRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnSplatRoute: EnSplatRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface EsRouteChildren {
  EsSplatRoute: typeof EsSplatRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsSplatRoute: EsSplatRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

interface EsMxRouteChildren {
  EsMxSplatRoute: typeof EsMxSplatRoute
}

const EsMxRouteChildren: EsMxRouteChildren = {
  EsMxSplatRoute: EsMxSplatRoute,
}

const EsMxRouteWithChildren = EsMxRoute._addFileChildren(EsMxRouteChildren)

interface FrRouteChildren {
  FrSplatRoute: typeof FrSplatRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrSplatRoute: FrSplatRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

interface ItRouteChildren {
  ItSplatRoute: typeof ItSplatRoute
}

const ItRouteChildren: ItRouteChildren = {
  ItSplatRoute: ItSplatRoute,
}

const ItRouteWithChildren = ItRoute._addFileChildren(ItRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  DeRoute: DeRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  EsRoute: EsRouteWithChildren,
  EsMxRoute: EsMxRouteWithChildren,
  FrRoute: FrRouteWithChildren,
  ItRoute: ItRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoriaProdutoRoute: CategoriaProdutoRoute,
  ComplianceAdsRoute: ComplianceAdsRoute,
  ComplianceCookiesRoute: ComplianceCookiesRoute,
  CompliancePrivacyRoute: CompliancePrivacyRoute,
  ComplianceReturnsRoute: ComplianceReturnsRoute,
  ComplianceTermsRoute: ComplianceTermsRoute,
  ApiPublicAbandonedCheckoutRoute: ApiPublicAbandonedCheckoutRoute,
  ApiPublicAliexpressReviewBrowserRoute: ApiPublicAliexpressReviewBrowserRoute,
  ApiPublicCommerceEventRoute: ApiPublicCommerceEventRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiPublicAliexpressStartRoute: ApiPublicAliexpressStartRoute,
  ApiPublicCronAliexpressStockRoute: ApiPublicCronAliexpressStockRoute,
  ApiPublicCronOrderEmailsRoute: ApiPublicCronOrderEmailsRoute,
  ApiPublicFeedsGoogleMerchantDotxmlRoute:
    ApiPublicFeedsGoogleMerchantDotxmlRoute,
  ApiPublicFeedsMetaCatalogDotcsvRoute: ApiPublicFeedsMetaCatalogDotcsvRoute,
  ApiPublicWebhooks17trackRoute: ApiPublicWebhooks17trackRoute,
  ApiPublicWebhooksAliexpressRoute: ApiPublicWebhooksAliexpressRoute,
  ApiPublicWebhooksAmplopayRoute: ApiPublicWebhooksAmplopayRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
  ApiPublicWebhooksEbanxRoute: ApiPublicWebhooksEbanxRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksNupayRoute: ApiPublicWebhooksNupayRoute,
  ApiPublicWebhooksPagbankRoute: ApiPublicWebhooksPagbankRoute,
  ApiPublicWebhooksPaypalRoute: ApiPublicWebhooksPaypalRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
