// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with elevated key - bypasses RLS.
// Use this only for trusted backend operations that genuinely require elevated access.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public project URL only. This is not a credential and is already shipped to the browser.
const PUBLIC_SUPABASE_URL = 'https://bnbksevtmbmlirnwglqb.supabase.co';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readServerEnv(name: string): string | undefined {
  if (typeof process === 'undefined' || !process.env) return undefined;
  const value = process.env[name];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function readNamedSecretKeySet(): string | undefined {
  const raw = readServerEnv('SUPABASE_SECRET_KEYS');
  if (!raw) return undefined;
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const preferred = parsed.default;
    if (typeof preferred === 'string' && preferred.trim()) return preferred.trim();
    const first = Object.values(parsed).find((value) => typeof value === 'string' && value.trim());
    return typeof first === 'string' ? first.trim() : undefined;
  } catch {
    return undefined;
  }
}

function resolveSupabaseAdminConfig(throwWhenMissing = true) {
  const url =
    readServerEnv('SUPABASE_URL') ||
    readServerEnv('VITE_SUPABASE_URL') ||
    PUBLIC_SUPABASE_URL;

  const adminKey =
    readServerEnv('SUPABASE_SECRET_KEY') ||
    readNamedSecretKeySet() ||
    readServerEnv('SUPABASE_SERVICE_ROLE_KEY');

  if (!adminKey) {
    if (!throwWhenMissing) return null;
    const message =
      'Supabase server secret is not configured. Set SUPABASE_SECRET_KEY (recommended) or SUPABASE_SERVICE_ROLE_KEY in the server environment.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (adminKey.startsWith('sb_publishable_')) {
    if (!throwWhenMissing) return null;
    throw new Error('SUPABASE_SECRET_KEY must be a server secret key, never a publishable key.');
  }

  return { url, adminKey };
}

function createSupabaseAdminClient(throwWhenMissing = true) {
  const config = resolveSupabaseAdminConfig(throwWhenMissing);
  if (!config) return null;
  const { url, adminKey } = config;

  return createClient<Database>(url, adminKey, {
    global: {
      fetch: createSupabaseFetch(adminKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

type SupabaseAdminClient = NonNullable<ReturnType<typeof createSupabaseAdminClient>>;
let _supabaseAdmin: SupabaseAdminClient | undefined;

/**
 * Returns the privileged client when the host actually has a server secret.
 * Normal authenticated admin screens must not depend on this helper; it exists
 * for Auth Admin, webhooks and other trusted backend-only operations.
 */
export function getSupabaseAdminOrNull(): SupabaseAdminClient | null {
  if (_supabaseAdmin) return _supabaseAdmin;
  const client = createSupabaseAdminClient(false);
  if (!client) return null;
  _supabaseAdmin = client;
  return client;
}

// Backward-compatible privileged client for true backend-only consumers.
// It remains lazy so importing the module itself never crashes a normal UI route.
export const supabaseAdmin = new Proxy({} as SupabaseAdminClient, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) {
      const client = createSupabaseAdminClient(true);
      if (!client) throw new Error('Supabase server secret is not configured.');
      _supabaseAdmin = client;
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
