// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with elevated key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public project URL only. This is not a credential and is already shipped to the browser.
// Keeping the URL fallback server-side prevents server functions from failing when the host
// does not inject SUPABASE_URL even though the application is connected to this project.
const PUBLIC_SUPABASE_URL = 'https://bnbksevtmbmlirnwglqb.supabase.co';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readServerEnv(name: string): string | undefined {
  if (typeof process === 'undefined' || !process.env) return undefined;
  const value = process.env[name];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function readNamedSecretKeySet(): string | undefined {
  const raw = readServerEnv('SUPABASE_SECRET_KEYS');
  if (!raw) return undefined;
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const preferred = parsed.default;
    if (typeof preferred === 'string' && preferred.trim()) return preferred.trim();
    const first = Object.values(parsed).find((value) => typeof value === 'string' && value.trim());
    return typeof first === 'string' ? first.trim() : undefined;
  } catch {
    return undefined;
  }
}

function resolveSupabaseAdminConfig() {
  const url =
    readServerEnv('SUPABASE_URL') ||
    readServerEnv('VITE_SUPABASE_URL') ||
    PUBLIC_SUPABASE_URL;

  // Supabase recommends the modern sb_secret_ key for backend code. Keep the
  // legacy service_role key as a compatible fallback during migration.
  const adminKey =
    readServerEnv('SUPABASE_SECRET_KEY') ||
    readNamedSecretKeySet() ||
    readServerEnv('SUPABASE_SERVICE_ROLE_KEY');

  if (!adminKey) {
    const message =
      'Supabase server secret is not configured. Set SUPABASE_SECRET_KEY (recommended) or SUPABASE_SERVICE_ROLE_KEY in the server environment.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (adminKey.startsWith('sb_publishable_')) {
    throw new Error('SUPABASE_SECRET_KEY must be a server secret key, never a publishable key.');
  }

  return { url, adminKey };
}

function createSupabaseAdminClient() {
  const { url, adminKey } = resolveSupabaseAdminConfig();

  return createClient<Database>(url, adminKey, {
    global: {
      fetch: createSupabaseFetch(adminKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with elevated privileges - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
